# Generated by Django 4.1.7 on 2023-03-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('matricula', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.BigAutoField(primary_key=True, serialize=False)),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(choices=[('atividade_casa', 'Atividade de casa'), ('atividade_sala', 'Atividade de sala'), ('prova', 'Prova')], max_length=50)),
                ('data_postagem', models.DateField()),
                ('data_entrega', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=7)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('codigo', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id_plano_aula', models.BigAutoField(primary_key=True, serialize=False)),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(max_length=50)),
                ('dia', models.DateField()),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina')),
            ],
            options={
                'verbose_name': 'Plano de aula',
                'verbose_name_plural': 'Planos de aula',
            },
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('presente', models.BooleanField(default=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.frequencia')),
            ],
            options={
                'verbose_name': 'Frequencia de alunos',
                'verbose_name_plural': 'Atribuir frequencia a alunos',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(default=0.0)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina')),
            ],
            options={
                'verbose_name': 'Matricula de aluno em disciplina',
                'verbose_name_plural': 'Matriculas de alunos em disciplina',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.professor'),
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.atividade')),
            ],
            options={
                'verbose_name': 'Avaliar aluno',
                'verbose_name_plural': 'Avaliações de alunos',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.planoaula'),
        ),
    ]
