# Generated by Django 4.1.7 on 2023-03-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lccv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadealuno',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
