# Generated by Django 4.1.7 on 2023-03-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lccv_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('presenca', models.BooleanField(default=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.aluno')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lccv_app.atividade')),
            ],
        ),
    ]
